// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Optional. The dev database is shared with the ERP fork, so `migrate dev`
    // would offer to reset away someone else's tables. Point this at a scratch
    // database and use `migrate diff --from-migrations` instead.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
